#!/bin/bash
set -e 
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Parse arguments
while [[ "$#" -gt 0 ]]; do
  case $1 in
    --config) CONFIG_PATH="$2"; shift ;;
    *) echo "Unknown parameter: $1"; exit 1 ;;
  esac
  shift
done

# Check if config is provided
if [ -z "$CONFIG_PATH" ]; then
  echo "Usage: $0 --config path_to_config.json"
  exit 1
fi

python3 -m jdex.main --config "$CONFIG_PATH"