"""Recover MHS explanations from explain operation logs.

This module extracts one explanation per prediction from log files generated by
the ``explain`` operation when using the MHS method. For each prediction block,
it returns the text after ``MUPS 1:`` when available, otherwise ``[]``.
"""

from __future__ import annotations

import csv
from datetime import datetime
from pathlib import Path
import re

from grainsack import logger
from grainsack.utils import read_json, write_json


def _read_predictions(predictions_path):
    path = Path(predictions_path)
    if path.suffix.lower() == ".json":
        data = read_json(path)
        if isinstance(data, list) and data and isinstance(data[0], dict) and "prediction" in data[0]:
            predictions = [list(item["prediction"]) for item in data]
            times = [item.get("time") for item in data]
            if all(time is None for time in times):
                times = None
            return predictions, times
        if isinstance(data, list) and data and isinstance(data[0], list):
            return [list(item) for item in data], None
        raise ValueError("Unsupported JSON prediction format.")

    predictions = []
    with open(path, "r", encoding="utf-8") as file_obj:
        sample = file_obj.read(2048)
        file_obj.seek(0)

        dialect = None
        try:
            dialect = csv.Sniffer().sniff(sample, delimiters="\t;,")
        except csv.Error:
            pass

        delimiter = dialect.delimiter if dialect is not None else "\t"
        reader = csv.reader(file_obj, delimiter=delimiter)

        first_row = next(reader, None)
        if first_row is None:
            return [], None

        normalized = [column.strip().lower() for column in first_row]
        has_header = len(normalized) >= 3 and normalized[:3] == ["s", "p", "o"]

        if not has_header:
            if len(first_row) >= 3:
                predictions.append(first_row[:3])

        for row in reader:
            if len(row) >= 3:
                predictions.append(row[:3])

    return predictions, None


def _read_times(times_path):
    data = read_json(times_path)
    if not isinstance(data, list):
        raise ValueError("times_path JSON must be a list.")

    times = []
    for item in data:
        if isinstance(item, dict):
            times.append(item.get("time"))
        else:
            times.append(None)
    return times


def _extract_prediction_index(line):
    marker = "Explaining prediction "
    position = line.find(marker)
    if position == -1:
        return None

    tail = line[position + len(marker):]
    number = ""
    for char in tail:
        if char.isdigit():
            number += char
        else:
            break

    if not number:
        return None
    return int(number) - 1


def _extract_mups_payload(line):
    marker = "MUPS 1:"
    position = line.find(marker)
    if position == -1:
        return None
    return line[position + len(marker):].strip()


def _extract_pellet_output_start(line):
    marker = "Pellet output:"
    position = line.find(marker)
    if position == -1:
        return None
    return line[position + len(marker):].lstrip()


def _extract_log_timestamp(line):
    try:
        return datetime.strptime(line[:19], "%Y-%m-%d %H:%M:%S")
    except ValueError:
        return None


def _parse_single_mhs_log(log_path, index_offset=0):
    explanations = {}
    times = {}

    current_prediction_index = None
    current_prediction_start = None
    last_timestamp = None
    collecting_pellet_output = False
    pellet_output_lines = []

    with open(log_path, "r", encoding="utf-8") as file_obj:
        for raw_line in file_obj:
            line = raw_line.rstrip("\n")

            timestamp = _extract_log_timestamp(line)
            if timestamp is not None:
                last_timestamp = timestamp

            if collecting_pellet_output:
                next_prediction_index = _extract_prediction_index(line)
                if "Pellet error output:" in line or next_prediction_index is not None:
                    if current_prediction_index is not None and current_prediction_index not in explanations:
                        pellet_output = "\n".join(pellet_output_lines).rstrip()
                        explanations[current_prediction_index] = pellet_output if pellet_output else []
                    collecting_pellet_output = False
                    pellet_output_lines = []
                    if "Pellet error output:" in line:
                        continue
                else:
                    pellet_output_lines.append(line)
                    continue

            maybe_index = _extract_prediction_index(line)
            if maybe_index is not None:
                if (
                    current_prediction_index is not None
                    and current_prediction_start is not None
                    and timestamp is not None
                    and current_prediction_index not in times
                ):
                    duration = (timestamp - current_prediction_start).total_seconds()
                    if duration >= 0:
                        times[current_prediction_index] = duration

                current_prediction_index = maybe_index + index_offset
                current_prediction_start = timestamp
                continue

            if current_prediction_index is None:
                continue

            mups_payload = _extract_mups_payload(line)
            if mups_payload is not None:
                explanations[current_prediction_index] = mups_payload
                continue

            pellet_output_start = _extract_pellet_output_start(line)
            if pellet_output_start is not None:
                collecting_pellet_output = True
                pellet_output_lines = [pellet_output_start]
                continue

            if "No abduction solution found" in line:
                explanations[current_prediction_index] = []
                continue

            if "AXIOM IS NOT ENTAILED" in line and current_prediction_index not in explanations:
                explanations[current_prediction_index] = []

    if collecting_pellet_output and current_prediction_index is not None and current_prediction_index not in explanations:
        pellet_output = "\n".join(pellet_output_lines).rstrip()
        explanations[current_prediction_index] = pellet_output if pellet_output else []

    if (
        current_prediction_index is not None
        and current_prediction_start is not None
        and last_timestamp is not None
        and current_prediction_index not in times
    ):
        duration = (last_timestamp - current_prediction_start).total_seconds()
        if duration >= 0:
            times[current_prediction_index] = duration

    return explanations, times


def _get_special_arco_complex_log_splits(log_path, predictions_count):
    if predictions_count > 200:
        return None

    primary = Path(log_path)
    if primary.name != "explain_ARCO25-5-MATERIALIZE_ComplEx_mhs_None2.log":
        return None

    split_23 = primary.with_name("explain_ARCO25-5-MATERIALIZE_ComplEx_mhs_None2_23.log")
    split_33 = primary.with_name("explain_ARCO25-5-MATERIALIZE_ComplEx_mhs_None2_33.log")

    if not split_23.exists() or not split_33.exists():
        return None

    return [
        (primary, 0),
        (split_23, 50),
        (split_33, 75),
    ]


def _get_special_arco_conve_20_log_splits(log_path, predictions_count):
    if predictions_count <= 0:
        return None

    primary = Path(log_path)
    match = re.match(r"^(?P<base>.+_mhs_None)_(?P<part>\d{1,2})20\.log$", primary.name)
    if match is None:
        return None

    base_name = match.group("base")
    split_logs = []
    for part in range(1, 21):
        split_log = primary.with_name(f"{base_name}_{part}20.log")
        if split_log.exists():
            split_logs.append((part, split_log))

    if not split_logs:
        return None

    split_logs.sort(key=lambda item: item[0])
    indexed_splits = []
    for part, split_log in split_logs:
        start_index = ((part - 1) * predictions_count) // 20
        indexed_splits.append((split_log, start_index))

    return indexed_splits


def _read_split_times_from_json(split_log_path):
    split_log = Path(split_log_path)
    json_name = split_log.name
    if json_name.startswith("explain_"):
        json_name = json_name[len("explain_"):]
    json_name = f"{Path(json_name).stem}.json"

    candidates = []
    if split_log.parent.name == "logs":
        candidates.append(split_log.parent.parent / "explanations" / json_name)
    candidates.append(split_log.with_name(json_name))

    selected_path = None
    for candidate in candidates:
        if candidate.exists():
            selected_path = candidate
            break

    if selected_path is None:
        return None

    return _read_times(selected_path)


def recover_mhs_explanations(predictions_path, log_path, output_path, times_path=None):
    """Recover one explanation per prediction from an MHS explain log.

    Args:
        predictions_path: Path to predictions input (TSV/CSV/JSON).
        log_path: Path to the explain log file.
        output_path: Destination JSON file.

    Returns:
        list[dict]: Items with keys ``prediction`` and ``explanation``.
    """
    predictions, times_from_predictions = _read_predictions(predictions_path)
    explanations = [None] * len(predictions)
    times = times_from_predictions

    if times_path is not None:
        times = _read_times(times_path)

    if times is not None and len(times) < len(predictions):
        times = times + [None] * (len(predictions) - len(times))

    special_splits = _get_special_arco_complex_log_splits(log_path, len(predictions))
    if special_splits is None:
        special_splits = _get_special_arco_conve_20_log_splits(log_path, len(predictions))

    if special_splits is not None:
        if times is None:
            split_json_times = [None] * len(predictions)
            has_split_json_times = False
            for split_log_path, index_offset in special_splits:
                times_for_split = _read_split_times_from_json(split_log_path)
                if times_for_split is None:
                    continue
                for local_index, duration in enumerate(times_for_split):
                    global_index = index_offset + local_index
                    if 0 <= global_index < len(split_json_times) and duration is not None:
                        split_json_times[global_index] = duration
                        has_split_json_times = True

            times = split_json_times if has_split_json_times else [None] * len(predictions)

        for split_log_path, index_offset in special_splits:
            split_explanations, split_times = _parse_single_mhs_log(split_log_path, index_offset=index_offset)

            for index, explanation in split_explanations.items():
                if 0 <= index < len(explanations) and explanations[index] is None:
                    explanations[index] = explanation

            for index, duration in split_times.items():
                if 0 <= index < len(times) and times[index] is None:
                    times[index] = duration
    else:
        parsed_explanations, parsed_times = _parse_single_mhs_log(log_path)

        for index, explanation in parsed_explanations.items():
            if 0 <= index < len(explanations) and explanations[index] is None:
                explanations[index] = explanation

        if parsed_times:
            if times is None:
                times = [None] * len(predictions)
            for index, duration in parsed_times.items():
                if 0 <= index < len(times) and times[index] is None:
                    times[index] = duration

    output = []
    recovered = 0
    empty = 0
    for index, (prediction, explanation) in enumerate(zip(predictions, explanations)):
        final_explanation = explanation if explanation is not None else []
        if final_explanation == []:
            empty += 1
        else:
            recovered += 1
        item = {"prediction": prediction, "explanation": final_explanation}
        if times is not None and index < len(times) and times[index] is not None:
            item["time"] = times[index]
        output.append(item)

    write_json(output, output_path)
    logger.info(
        "Recovered explanations written to %s (recovered=%d, empty=%d, total=%d)",
        output_path,
        recovered,
        empty,
        len(output),
    )

    return output
